### ISSUE TITLE
Class goals

### ISSUE THREAD

**Issue by hubyeti** [swinful/github-for-developers-7#1]
Please tell us one thing you would like to learn in today's class!

**Comment by swinful** [comment]
Merging pull-requests

On Wed, Nov 25, 2015 at 10:39 AM, Certify Yeti <notifications@github.com>
wrote:

> Please tell us one thing you would like to learn in today's class!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swinful/github-for-developers-7/issues/1>.
>



-- 
Samuel A. Winful, http://wellrounded.wordpress.com

"God uses you wherever you are.
   And where you are is your ministry."
       -William H. Myers

**Comment by swinful** [comment]
Replied with one goal as instructed.
